### ISSUE TITLE
Идея: как написать бота для Телеграма, если ты знаешь только JS

### ISSUE THREAD

**Issue by sashasushko** [UralJS/talks#7]
Пока сам не копал тему, хотел бы, чтобы кто-то раскопал. Потому что хочу написать бота, а знаю только JS. Не уверен, что этого достаточно. Даже если этот JS - Node.js

Нужен тот, кто разберётся и расскажет.

**Comment by igorlukanin** [comment]
Пф! https://github.com/igorlukanin/wide-river-canteen-camera-bot

**Comment by sashasushko** [comment]
Кажется, кто-то готов рассказать ;-)

**Comment by vansosnin** [comment]
Это же JS, для всего есть пакет в npm :)
Я использовал https://github.com/yagop/node-telegram-bot-api
Пример: https://github.com/vansosnin/billy-tc-bot

**Comment by ssnikiforov** [comment]
Пример:
https://github.com/fletcherist/2018-elections-big-brother
Самого бота можно потрогать здесь: 
http://t.me/elections_2018bot
